/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

/**
 *
 * @author dsom1
 */
public class pnlReto extends javax.swing.JPanel {

    /**
     * Creates new form pnlReto
     */
    public pnlReto() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPreguntas = new javax.swing.JButton();
        btnCompletar = new javax.swing.JButton();
        pnlTer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(670, 440));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(16, 33, 59));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPreguntas.setBackground(new java.awt.Color(16, 33, 59));
        btnPreguntas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/molecula.png"))); // NOI18N
        btnPreguntas.setToolTipText("");
        btnPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreguntasActionPerformed(evt);
            }
        });
        jPanel1.add(btnPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 70, 70));

        btnCompletar.setBackground(new java.awt.Color(16, 33, 59));
        btnCompletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cuaderno.png"))); // NOI18N
        btnCompletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompletarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCompletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 70, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 70, 440));

        pnlTer.setBackground(new java.awt.Color(255, 255, 255));
        pnlTer.setLayout(new javax.swing.BoxLayout(pnlTer, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/f7.jpg"))); // NOI18N
        pnlTer.add(jLabel1);

        add(pnlTer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 440));
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreguntasActionPerformed
        new CambiaPanel(pnlTer, new Preguntas());
    }//GEN-LAST:event_btnPreguntasActionPerformed

    private void btnCompletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompletarActionPerformed
        new CambiaPanel(pnlTer, new Completar());
    }//GEN-LAST:event_btnCompletarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompletar;
    private javax.swing.JButton btnPreguntas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlTer;
    // End of variables declaration//GEN-END:variables
}
